package ee.markkuskoodi.c4generator.export;

import ee.markkuskoodi.c4generator.model.Container;
import ee.markkuskoodi.c4generator.model.ContainerKind;
import ee.markkuskoodi.c4generator.model.Model;
import ee.markkuskoodi.c4generator.model.Relationship;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Emits a Structurizr DSL workspace with a container view (FR-OUT-1). DSL identifiers
 * are deterministic sanitizations of the stable model ids, so re-exports of the same
 * model are byte-identical (NFR-2) and diagram links stay stable across generations.
 */
public final class StructurizrDslExporter implements Exporter {

    private static final String DATA_STORE_TAG = "Data Store";

    @Override
    public String fileName() {
        return "workspace.dsl";
    }

    @Override
    public String export(Model model) {
        Map<String, String> dslIds = dslIdentifiers(model);
        Map<String, String> displayNames = displayNames(model);
        String systemId = "sys";
        StringBuilder dsl = new StringBuilder();
        dsl.append("workspace \"").append(escape(model.system().name()))
                .append("\" \"Generated by c4-generator-service. Do not edit by hand.\" {\n\n");
        dsl.append("    model {\n");
        dsl.append("        ").append(systemId).append(" = softwareSystem \"")
                .append(escape(model.system().name())).append("\" {\n");
        for (Container container : model.containers()) {
            dsl.append("            ").append(dslIds.get(container.id()))
                    .append(" = container \"").append(escape(displayNames.get(container.id())))
                    .append("\" \"\" \"").append(escape(container.technology())).append("\"");
            if (container.kind() == ContainerKind.DATA_STORE) {
                dsl.append(" \"").append(DATA_STORE_TAG).append("\"");
            }
            dsl.append("\n");
        }
        for (Relationship relationship : model.relationships()) {
            dsl.append("            ").append(dslIds.get(relationship.sourceId()))
                    .append(" -> ").append(dslIds.get(relationship.targetId()))
                    .append(" \"").append(escape(relationship.description()))
                    .append("\" \"").append(escape(relationship.technology())).append("\"\n");
        }
        dsl.append("        }\n");
        dsl.append("    }\n\n");
        dsl.append("    views {\n");
        dsl.append("        container ").append(systemId).append(" \"Containers\" {\n");
        dsl.append("            include *\n");
        dsl.append("            autoLayout\n");
        dsl.append("        }\n");
        dsl.append("        styles {\n");
        dsl.append("            element \"").append(DATA_STORE_TAG).append("\" {\n");
        dsl.append("                shape cylinder\n");
        dsl.append("            }\n");
        dsl.append("        }\n");
        dsl.append("    }\n");
        dsl.append("}\n");
        return dsl.toString();
    }

    /**
     * Model id -> display name. Structurizr requires container names to be unique
     * within a software system; the model does not (two databases named alike on
     * different products). Duplicates are disambiguated with the technology, then a
     * numeric suffix, in model-id order — deterministic.
     */
    private Map<String, String> displayNames(Model model) {
        Map<String, Long> nameCounts = new LinkedHashMap<>();
        for (Container container : model.containers()) {
            nameCounts.merge(container.name(), 1L, Long::sum);
        }
        Map<String, String> byModelId = new LinkedHashMap<>();
        Map<String, Integer> used = new LinkedHashMap<>();
        for (Container container : model.containers()) {
            String name = nameCounts.get(container.name()) > 1
                    ? container.name() + " (" + container.technology() + ")"
                    : container.name();
            int count = used.merge(name, 1, Integer::sum);
            byModelId.put(container.id(), count == 1 ? name : name + " " + count);
        }
        return byModelId;
    }

    /**
     * Model id -> DSL identifier. Sanitization can collide (':' and '.' both map to
     * '_'); collisions get a numeric suffix in model-id order, which is deterministic.
     */
    private Map<String, String> dslIdentifiers(Model model) {
        Map<String, String> byModelId = new LinkedHashMap<>();
        Map<String, Integer> used = new LinkedHashMap<>();
        for (Container container : model.containers()) {
            String base = sanitize(container.id());
            int count = used.merge(base, 1, Integer::sum);
            byModelId.put(container.id(), count == 1 ? base : base + "_" + count);
        }
        return byModelId;
    }

    private static String sanitize(String modelId) {
        String candidate = modelId.replaceAll("[^A-Za-z0-9_]", "_");
        return Character.isLetter(candidate.charAt(0)) ? candidate : "e_" + candidate;
    }

    private static String escape(String value) {
        return value == null ? "" : value.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}